global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'kafka-system-monitor'

rule_files:
  # - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
    - targets:
      - '43.201.13.181:9308'
      labels:
        env: 'kafka-dev-env'

  - job_name: 'zookeeper'
    static_configs:
    - targets:
      - '43.201.13.181:7075'
      - '43.200.251.62:7075'
      - '52.78.78.140:7075'
      labels:
        env: 'kafka-dev-env'

  - job_name: 'kafka-connect'
    static_configs:
      - targets:
          - '43.201.13.181:7075'
        labels:
          env: 'kafka-dev-env'
