name: Deploy to Kafka Components

on:
  push:
    paths:
      - 'kafka-component/**'
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Push to kafka-components EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Add public IP to AWS security group
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'
      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KAFKA_SIDE_CAR_PRIVATE_SSH_PRIVATE_KEY }}
          SOURCE: "kafka-component/"
          REMOTE_HOST: ${{ secrets.KAFKA_COMPONENTS_REMOTE_HOST }}
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/kafka-components"
