name: Sync Airflow Components to ec2
on:
  push:
    paths:
      - 'airflow-dev-env/**'

jobs:
  deploy:
    name: Push to airflow EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Add public IP to AWS security group
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'
      - name: sync docker components to EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KAFKA_SIDE_CAR_PRIVATE_SSH_PRIVATE_KEY }}
          SOURCE: "airflow-dev-env/"
          REMOTE_HOST: ${{ secrets.AIRFLOW_EC2_REMOTE_HOST }}
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/airflow"
      - name: Restart Docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AIRFLOW_EC2_REMOTE_HOST }}
          username: "ec2-user"
          key: ${{ secrets.KAFKA_SIDE_CAR_PRIVATE_SSH_PRIVATE_KEY }}
          port: '22'
          script: |
            cd /home/ec2-user/airflow
            docker system prune -a
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -a -q)
            docker-compose up -d
